// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZaLQ7s2CLKH51orrsbK8-7rNvt0FEU0',
    appId: '1:149978646644:android:60712bcda93be0e8c96921',
    messagingSenderId: '149978646644',
    projectId: 'appmovilesproject',
    storageBucket: 'appmovilesproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP7L0-tccTitD18w3HJtjcQhH9YXHDDbU',
    appId: '1:149978646644:ios:223e2711fbdec86ec96921',
    messagingSenderId: '149978646644',
    projectId: 'appmovilesproject',
    storageBucket: 'appmovilesproject.appspot.com',
    androidClientId: '149978646644-mr210ukk6g7l2mceiqtvi5d8p634u810.apps.googleusercontent.com',
    iosClientId: '149978646644-hsp5g9qedsmc3mdneetghrcipd0ngedp.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGrouptask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP7L0-tccTitD18w3HJtjcQhH9YXHDDbU',
    appId: '1:149978646644:ios:223e2711fbdec86ec96921',
    messagingSenderId: '149978646644',
    projectId: 'appmovilesproject',
    storageBucket: 'appmovilesproject.appspot.com',
    androidClientId: '149978646644-mr210ukk6g7l2mceiqtvi5d8p634u810.apps.googleusercontent.com',
    iosClientId: '149978646644-hsp5g9qedsmc3mdneetghrcipd0ngedp.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGrouptask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZKe-0me2sS0E96pCkbwcI7D3zBG9wym8',
    appId: '1:149978646644:web:ec4fd692967661b8c96921',
    messagingSenderId: '149978646644',
    projectId: 'appmovilesproject',
    authDomain: 'appmovilesproject.firebaseapp.com',
    storageBucket: 'appmovilesproject.appspot.com',
    measurementId: 'G-JENPP87950',
  );
}
